### ISSUE TITLE
Lv.1 페어 리뷰입니다

### ISSUE THREAD

**Issue by iksadNorth** [haechanlee96/post#2]
- 완성도 있는 부분
    - Post Entity를 설계하실 때, 
    @Column 어노테이션을 이용해서 꼼꼼하게 각 칼럼의 스펙을 적어주신 점이 좋았습니다.
    - TimeStamped Class 설계로 확장성을 높인 것이 좋았습니다.
    - 주석을 꼼꼼하게 작성하셔서 가독성을 높인 점이 좋았습니다

- 수정, 삭제 API의 request를 어떤 방식으로 사용하신 방식
수정에서는 RequestDto라는 DTO를 이용해서 Body의 데이터를 파싱하신 것으로 보입니다.
@RequestBody를 이용해서 요청의 내용을 받으신 것으로 이와 같이 생각했습니다.
삭제에서도 RequestDto라는 DTO를 이용해서 Body의 데이터를 파싱하신 것으로 봤습니다.
마찬가지로 @ReqeustBody를 이용해서 요청의 내용을 받으셨습니다.

- 어떤 상황에 어떤 방식의 request를 사용하셨는지?
Post, Put에서의 요청은 데이터를 Body에 담아서 보내야 하는 것으로 알고 있고
Get, Delete에서의 요청은 데이터를 PathVariable 혹은 Parameter 형태로 보내야 하는 것으로 알고 있습니다.
https://www.inflearn.com/questions/460311/delete-%EC%9D%98-body-%EC%82%AC%EC%9A%A9%EC%97%90-%EB%8C%80%ED%95%B4%EC%84%9C-%EA%B6%81%EA%B8%88%ED%95%A9%EB%8B%88%EB%8B%A4
![image](https://github.com/haechanlee96/post/assets/66674140/bca36d7c-87d7-4235-b27c-f49169524cd3)

- RESTful한 API를 설계하셨는지 여부
해찬님은 각 API를 다음과 같은 End Point로 설계해주셨습니다.

1. 게시글 작성
POST /api/post
2. 게시글 전체 조회
GET /api/posts
3. 선택한 게시글 조회
GET /api/post/{id}
4. 게시글 수정
PUT /api/post/{id}
5. 게시글 삭제
DELETE /api/post/{id}

위와 같이 Method와 URL 만으로도 자원을 어떻게 가공하고 조회할 것인지에 대해 
이해하기 쉽게 End Point를 작성해주셨습니다.
각 메서드가 알맞게 CRUD를 표현했고 어떤 자원을 대상으로 하는지도 URL로 표현해주셨습니다.

- 적절한 관심사 분리를 적용하셨는지
Controller에서는 api의 End Point 정의, 데이터 취득방법에 대한 코드만 작성하시고
Repository에서는 DB와 소통을 하기 위한 코드만 작성하셨고
Service에서는 비즈니스 코드를 작성하시면서 관심사 분리를 적용하셨습니다.

**Comment by haechanlee96** [comment]
넵 감사합니다

업데이트나 삭제 부분에서 RequestBody를 직접 담지 않고 다른 방법을 통해서 시도해보겠습니다!
